version: '3.9'

services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretps
      POSTGRES_DB: hw12
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data
